Fix asset management feature flag
This was added in 5f96d3005d74283e1e717f3f9c54ac2b743e216a but there was
no test for the feature flag logic.

When the feature flag is off, the controller methods return the error:

```
NoMethodError:
       undefined method 'asset' for true
```

This meant that we would log an unhelpful error message, when if fact
the issue was the feature flag is disabled. As there is no action for us
to take, it makes more sense to inform the user.

Therefore updating the feature flag to return a response to the user
(instead of logging to Sentry) and adding tests to check this.