Update Plek to 1.11.0
We're planning on querying Content Register for a Manual's topics, and it
expects a more recent version of Plek.

The error looked something like:
in `<module:ContentRegister>': undefined method `find' for Plek:Class (NoMethodError)