Add `listen` gem to development group
This gem is need to run sidekiq.

```
bundler: failed to load command: sidekiq
(/usr/lib/rbenv/versions/2.3.1/bin/sidekiq)
LoadError: Could not load the 'listen' gem. Add `gem 'listen'` to the
development group of your Gemfile
```