Fix missing asset_home error
We are currently getting this error in the app:
```
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x000056021751d640>
Did you mean?  asset_host
  /app/vendor/bundle/ruby/2.7.0/gems/railties-7.0.2.3/lib/rails/railtie/configuration.rb:96:in `method_missing'
  /app/config/environments/production.rb:28:in `block in <top (required)>'
  /app/vendor/bundle/ruby/2.7.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:251:in `instance_eval'
  /app/vendor/bundle/ruby/2.7.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:251:in `configure'
  /app/config/environments/production.rb:3:in `<top (required)>'
```

This commit fixes that.

Ref:
1. [pr removing asset initializer](#670)